namespace BackendGameVibes.Helpers {
    public class DbInitializerData {
        public static readonly List<string> RandomUsernames = [
            "TechGuru",
            "ShadowHunter",
            "PixelMaster",
            "CodeCracker",
            "DevChampion",
            "GameNinja",
            "PixelWizard",
            "CyberRogue",
            "CodePhoenix",
            "DarkKnightX",
            "GlitchMancer",
            "QuantumCoder",
            "ZeroX",
            "PixelPanda",
            "NightWolf",
            "EpicCoder",
            "SilentStorm",
            "CodeViper",
            "SkyWalker42",
            "BinaryBeast"
        ];

        public static readonly string[] LoremIpsumWords = [
            "lorem", "ipsum", "dolor", "sit", "amet", "consectetur",
            "adipiscing", "elit", "sed", "do", "eiusmod", "tempor", "incididunt",
            "ut", "labore", "et", "dolore", "magna", "aliqua"
        ];

        public static readonly string[] ForumThreadsTitles = [
            "Czy ktoś już grał w najnowszą część serii i może podzielić się opinią?",
            "Jakie są wasze ulubione gry na odprężenie po ciężkim dniu?",
            "Mam problem z uruchomieniem gry po ostatniej aktualizacji. Ktoś miał podobny problem?",
            "Ktoś chętny na wspólne granie w ten weekend?",
            "Czy macie jakieś porady dla początkującego gracza?",
            "Jakie gry najbardziej wciągnęły was w ostatnich miesiącach?",
            "Jaka jest wasza ulubiona klasa postaci w grach RPG i dlaczego?",
            "Czy ktoś ma sprawdzone sposoby na optymalizację FPS w tej grze?",
            "Jakie dodatki polecacie do tej gry?",
            "Czy wiecie coś o nadchodzących aktualizacjach?",
            "Co sądzicie o mikrotransakcjach w tej grze?",
            "Macie jakieś doświadczenia z trybem kooperacji? Czy warto zagrać z kimś?",
            "Szukam ekipy do gry wieloosobowej, ktoś chętny?",
            "Która gra według was ma najlepszą fabułę?",
            "Czy opłaca się kupować rozszerzenie do tej gry, czy lepiej poczekać?",
            "Jakie gry polecacie na konsole nowej generacji?",
            "Z jakich postaci lub umiejętności najczęściej korzystacie?",
            "Jakie są wasze ulubione bronie lub zestawy w tej grze?",
            "Słyszeliście o nadchodzącej wersji VR tej gry?",
            "Która gra ma według was najbardziej satysfakcjonujący system walki?",
            "Jakie gry indie polecacie? Szukam czegoś nietypowego.",
            "Czy ktoś próbował modów do tej gry? Jakie warto zainstalować?",
            "Co myślicie o mechanice rozwoju postaci w tej grze?",
            "Jakie są wasze sposoby na szybkie zdobycie waluty w tej grze?",
            "Czy wolicie grać solo czy w drużynie w tej grze?",
            "Która część tej serii była według was najlepsza i dlaczego?",
            "Jaką strategię polecacie na wyższych poziomach trudności?",
            "Czy ktoś ma informacje o przyszłych wydarzeniach w grze?",
            "Jakie są wasze ulubione tryby gry wieloosobowej?",
            "Czy zdarzyło wam się kiedyś znaleźć ukryte sekrety w tej grze?"
        ];

        public static readonly string[] PostContent = [
            "Grafika w tej grze jest niesamowita, naprawdę przyciąga wzrok. Każdy szczegół świata jest dopracowany, co czyni eksplorację przyjemnością. Uwielbiam sposób, w jaki świat ożywa dzięki realistycznym efektom oświetlenia.",
            "System walki w tej grze jest bardzo płynny i daje dużo satysfakcji. Każdy cios wydaje się mieć odpowiednią wagę, a kombinacje ruchów są intuicyjne. Często łapię się na tym, że walczę tylko dla samej przyjemności rozgrywki.",
            "Uwielbiam eksplorować otwarty świat pełen sekretów i ukrytych lokacji. Zawsze znajduje się coś nowego do odkrycia, co sprawia, że gra nigdy się nie nudzi. Twórcy naprawdę zadbali o szczegóły, które budują klimat.",
            "Postacie w tej grze są dobrze napisane i łatwo się z nimi utożsamić. Ich historie są głębokie, a dialogi realistyczne. Czuję, jakbym faktycznie poznawał prawdziwe osoby podczas gry.",
            "Muzyka w tle dodaje klimatu i sprawia, że gra jest bardziej wciągająca. Ścieżka dźwiękowa idealnie dopasowuje się do wydarzeń na ekranie. W wielu momentach to właśnie muzyka buduje napięcie.",
            "Misje poboczne są równie interesujące jak główna fabuła. Często są pełne niespodzianek i ciekawych zwrotów akcji. Niektóre z nich zapadają w pamięć bardziej niż główny wątek.",
            "Gra ma świetny balans między trudnością a przyjemnością z rozgrywki. Nawet najtrudniejsze momenty nie frustrują, a raczej motywują do działania. Czuć, że twórcy przemyśleli każdy aspekt rozgrywki.",
            "Animacje postaci są bardzo realistyczne i dodają głębi każdej akcji. Nawet drobne gesty są dobrze odwzorowane. Dzięki temu immersja w świat gry jest naprawdę wysoka.",
            "Klimat tej gry jest mroczny, ale wciąga i nie pozwala odejść. Twórcy doskonale oddali atmosferę grozy, a jednocześnie zachowali równowagę, by gra nie była przytłaczająca. To prawdziwy majstersztyk.",
            "Fabuła jest bardzo złożona i pełna niespodziewanych zwrotów akcji. Z każdym kolejnym etapem dowiaduję się nowych, zaskakujących rzeczy. Czuję, że jestem częścią czegoś naprawdę wyjątkowego.",
            "System rozwoju postaci jest dobrze przemyślany i daje dużo możliwości. Mogę dostosować swojego bohatera do własnego stylu gry. To sprawia, że każda rozgrywka jest unikalna.",
            "Tryb wieloosobowy to świetna zabawa, szczególnie z przyjaciółmi. Wspólne planowanie strategii i realizacja zadań daje mnóstwo frajdy. To idealny sposób na spędzenie wieczoru.",
            "Pogoda i cykl dnia i nocy wpływają na gameplay, co jest ciekawym dodatkiem. Niektóre misje zmieniają się w zależności od pory dnia. Dzięki temu świat gry wydaje się żywy.",
            "Zadania w grze są różnorodne i nigdy się nie nudzą. Każde z nich wymaga innego podejścia i pozwala na kreatywność. Czuję, że naprawdę rozwijam swoje umiejętności jako gracz.",
            "Gra ma wiele zakończeń, co zachęca do jej przejścia kilka razy. Każde zakończenie jest satysfakcjonujące i pokazuje inne aspekty fabuły. Uwielbiam gry, które nagradzają eksplorację różnych ścieżek.",
            "Klimatyczne lokacje sprawiają, że czuję się, jakbym tam naprawdę był. Każde miejsce jest unikalne i pełne detali, które budują atmosferę. Często zatrzymuję się tylko po to, by podziwiać widoki.",
            "Interfejs użytkownika jest przejrzysty i łatwy do opanowania. Wszystko jest na swoim miejscu i intuicyjne. Dzięki temu mogę skupić się na rozgrywce, a nie na szukaniu opcji.",
            "Ostatnia aktualizacja wprowadziła wiele nowych funkcji i usprawnień. Gra działa teraz jeszcze płynniej, a nowe elementy są naprawdę interesujące. Twórcy pokazali, że słuchają społeczności graczy.",
            "Gra jest pełna ukrytych przedmiotów, które dodają głębi rozgrywce. Szukanie ich to świetna zabawa, która wynagradza eksplorację. Niektóre z nich mają ciekawe historie lub dodatkowe funkcje.",
            "Rozwój bohatera zależy od naszych wyborów, co daje poczucie wolności. Każda decyzja ma swoje konsekwencje, co sprawia, że gra jest bardziej angażująca. To naprawdę unikalne doświadczenie.",
            "Gra została zoptymalizowana i działa płynnie na moim sprzęcie. Nawet na średnich ustawieniach wygląda świetnie i nie traci na płynności. Twórcy naprawdę przyłożyli się do optymalizacji.",
            "System craftingu jest rozbudowany i satysfakcjonujący. Mogę tworzyć różne przedmioty, które pomagają mi w rozgrywce. Czasem samo zbieranie materiałów daje dużo frajdy.",
            "Każdy region w grze ma swój unikalny klimat i charakter. Od pustyń po ośnieżone góry, każde miejsce zapada w pamięć. Czuję, że każda podróż jest prawdziwą przygodą.",
            "Odwiedzane lokacje są zróżnicowane i zapadają w pamięć. Każda z nich ma swoją historię, którą odkrywam podczas gry. Uwielbiam, gdy gra oferuje tak bogaty świat.",
            "Postacie niezależne mają swoje unikalne historie i osobowości. Często angażują mnie w swoje problemy, co dodaje głębi fabule. Czuję, że to żywy świat, pełen ludzi z krwi i kości.",
            "Walka z bossami wymaga strategii i dobrego przygotowania. Każdy boss jest inny i zmusza do dostosowania taktyki. Pokonanie ich daje ogromną satysfakcję.",
            "Broń i ekwipunek można modyfikować, co urozmaica rozgrywkę. Dzięki temu każda broń może być dostosowana do mojego stylu gry. To świetny sposób na personalizację rozgrywki.",
            "Odkrywanie sekretów i znajdziek to jedna z największych przyjemności w grze. Każdy zakątek mapy kryje coś interesującego. Często czuję się jak odkrywca na tropie skarbu.",
            "System punktów doświadczenia pozwala na rozwijanie różnych umiejętności. Mogę inwestować w to, co naprawdę mnie interesuje, co daje poczucie kontroli nad postacią. Dzięki temu gra staje się jeszcze bardziej wciągająca.",
            "Gra zachęca do eksploracji i wynagradza za ciekawość gracza. Często przypadkowe zejście z trasy prowadzi do fascynujących odkryć. Uwielbiam, gdy gra nagradza moją dociekliwość.",
            "Grałem już w najnowszą część i muszę przyznać, że fabuła jest naprawdę zaskakująca. Nie chcę spoilerować, ale przygotujcie się na kilka emocjonalnych momentów. System walki też został znacznie usprawniony.",
            "Jeśli szukasz gier na odprężenie, polecam Stardew Valley. Możesz spokojnie uprawiać ogród, rozmawiać z mieszkańcami i cieszyć się spokojnym klimatem. To idealna gra na relaks po ciężkim dniu.",
            "Miałem ten sam problem z uruchomieniem gry po aktualizacji. Udało mi się go rozwiązać przez ponowną instalację sterowników karty graficznej. Może warto spróbować tej metody?",
            "Ja jestem chętny na wspólne granie w weekend! Może uda się zebrać większą ekipę? Jak coś, to podajcie godziny, które wam pasują.",
            "Dla początkującego gracza najlepsza rada to nie zniechęcać się początkowymi trudnościami. Każda gra wymaga trochę czasu, żeby ją dobrze poznać. Warto też poszukać poradników lub filmików na YouTube.",
            "Ostatnio wciągnąłem się w Baldur's Gate 3. Świetna fabuła i niesamowicie rozbudowane postacie. Polecam każdemu fanowi gier RPG.",
            "Moja ulubiona klasa w grach RPG to mag, bo lubię rzucać potężne czary i kontrolować pole walki. A wy, czym gracie najczęściej? Wojownik czy może coś bardziej zwinnego?",
            "Jeśli chodzi o optymalizację FPS, to zmniejszenie cieni w ustawieniach graficznych bardzo pomogło. U mnie różnica była naprawdę widoczna. Może też warto zaktualizować sterowniki karty graficznej?",
            "Do tej gry polecam dodatek 'Frozen Realms'. Wprowadza nową fabułę, sporo wyzwań i przepiękne lokacje. Zdecydowanie wart swojej ceny.",
            "Podobno w nadchodzącej aktualizacji mają dodać nowy tryb kooperacji. Nie mogę się doczekać, aż wypróbuję to z ekipą! Ciekawe, jakie jeszcze nowości nas czekają.",
            "Mikrotransakcje są w tej grze trochę irytujące, ale da się bez nich grać. Warto korzystać z darmowych nagród, które pojawiają się co jakiś czas. Jak wy sobie z tym radzicie?",
            "Tryb kooperacji jest super, jeśli masz z kim grać. Sam przeszedłem większość misji ze znajomymi i mieliśmy masę zabawy. Czasem nawet najprostsze zadania stają się wyzwaniem, gdy próbujecie działać zespołowo.",
            "Szukasz ekipy? To jestem chętny! Może uda się zebrać kilka osób na większą misję. Jak coś, daj znać, w co gramy.",
            "Jeśli chodzi o najlepszą fabułę, to chyba The Last of Us wygrywa u mnie. Historia jest tak emocjonalna, że trudno było mi oderwać się od ekranu. Co wy byście polecili w tej kategorii?",
            "Według mnie warto kupić rozszerzenie, jeśli podobała ci się podstawowa wersja gry. Daje to nowe misje i ulepszenia, które znacznie wydłużają zabawę. Ale jeśli masz ograniczony budżet, poczekaj na promocję.",
            "Na konsolę nowej generacji zdecydowanie polecam Cyberpunk 2077 po ostatnich aktualizacjach. Działa płynnie i wygląda niesamowicie. Jakie jeszcze gry byście polecili?",
            "Najczęściej korzystam z łuku, bo lubię walczyć na dystans i eliminować przeciwników po cichu. Jak wy gracie? Bardziej z bliska czy też na dystans?",
            "Ulubiona broń w tej grze to u mnie dwuręczny miecz. Czuję, że każdy cios robi ogromne obrażenia. A wy, co najczęściej wybieracie?",
            "Słyszałem, że wersja VR tej gry będzie miała dodatkowe funkcje, jak dokładniejsze odwzorowanie ruchów. Nie mogę się doczekać, aż spróbuję. Myślicie, że to zmieni sposób grania?",
            "System walki w tej grze jest bardzo satysfakcjonujący, bo każdy przeciwnik wymaga innej taktyki. Uwielbiam takie wyzwania. Jak wy podchodzicie do walki? Agresywnie czy bardziej defensywnie?"
        ];

        public static readonly string[] ReviewContent = [
            "Grafika w tej grze jest po prostu zachwycająca. Detale otoczenia, animacje i oświetlenie są na najwyższym poziomie. Każda lokacja wygląda, jakby została stworzona z ogromną dbałością o szczegóły. Podczas eksploracji świata gry można dostrzec mnóstwo ukrytych elementów, które cieszą oko. Gra działa płynnie nawet na starszym sprzęcie, co jest dużym plusem. Twórcy zadbali o optymalizację, dzięki czemu doświadczenie z gry jest niezakłócone.",
            "System walki w tej grze to mistrzostwo. Każda potyczka wymaga myślenia i szybkich reakcji. Możliwość łączenia różnych ataków w kombinacje sprawia, że każda walka jest unikalna. Umiejętności postaci są różnorodne i dają wiele możliwości eksperymentowania. Przeciwnicy różnią się zachowaniem, co wymusza zmianę strategii. Dzięki temu gra nie staje się monotonna, a każda walka jest wyzwaniem.",
            "Otwarty świat tej gry to coś niesamowitego. Każdy zakątek kryje tajemnice i sekrety do odkrycia. Świat jest pełen życia, z dynamicznymi wydarzeniami, które dzieją się wokół gracza. Twórcy zadbali, by każde miejsce miało unikalny klimat i historię. Eksploracja jest nie tylko przyjemnością, ale również nagradzana jest znajdźkami i ukrytymi przedmiotami.",
            "Postacie w tej grze są jednymi z najlepiej napisanych, jakie widziałem. Ich dialogi są naturalne i pełne emocji. Każda postać ma własną historię, którą można poznać w trakcie gry. Relacje między postaciami są wiarygodne i rozwijają się w ciekawy sposób. Dzięki temu łatwo się z nimi utożsamić, a ich losy naprawdę obchodzą gracza.",
            "Muzyka w tej grze jest piękna i idealnie dopasowana do klimatu. Ścieżka dźwiękowa zmienia się w zależności od sytuacji, budując napięcie lub wprowadzając nastrój relaksu. Motywy przewodnie łatwo zapadają w pamięć i nadają grze charakteru. Dźwięki otoczenia, takie jak szum lasu czy odgłosy miasta, są równie imponujące i wciągają gracza jeszcze głębiej w świat gry.",
            "Misje poboczne w tej grze to coś więcej niż zwykłe zadania. Każda z nich ma własną historię, która potrafi być równie wciągająca jak główna fabuła. Twórcy zadbali o różnorodność wyzwań, dzięki czemu nie ma poczucia powtarzalności. Niektóre misje odkrywają nowe lokacje lub postacie, co zachęca do ich wykonywania. Nagrody za misje poboczne są wartościowe i naprawdę warte wysiłku.",
            "Balans trudności w tej grze jest idealny. Początkowe etapy pozwalają graczowi oswoić się z mechaniką, ale później gra staje się coraz bardziej wymagająca. Każda walka i każda łamigłówka wymagają odpowiedniego przygotowania. Sukces jest bardzo satysfakcjonujący i daje poczucie osiągnięcia czegoś wyjątkowego. Gra nie jest ani za łatwa, ani zbyt frustrująca.",
            "Animacje w tej grze są na najwyższym poziomie. Postacie poruszają się płynnie i naturalnie, co dodaje realizmu. Nawet najmniejsze detale, takie jak ruchy włosów czy mimika twarzy, są dopracowane. Dzięki temu każda scena wygląda jak żywa. To sprawia, że gra ogląda się jak film.",
            "Klimat gry jest niesamowicie wciągający. Mroczna atmosfera świata sprawia, że chce się dowiedzieć więcej o jego historii. Nawet gdy gra staje się trudna, klimat zachęca do dalszej gry. Wszystko, od projektów lokacji po muzykę i fabułę, tworzy spójną i przyciągającą całość.",
            "Fabuła w tej grze jest jak dobra książka – nie mogłem się oderwać. Jest pełna zwrotów akcji i tajemnic do odkrycia. Każda decyzja, jaką podejmuje gracz, ma wpływ na rozwój historii. Dzięki temu mam poczucie, że naprawdę uczestniczę w tworzeniu tej opowieści. Zakończenia są różnorodne i zachęcają do wielokrotnego przechodzenia gry.",
            "System rozwoju postaci w tej grze daje ogromną swobodę. Mogę wybierać umiejętności, które najlepiej pasują do mojego stylu gry. Nie ma jedynej słusznej drogi, co dodaje głębi rozgrywce. Możliwość eksperymentowania z różnymi stylami gry sprawia, że każda sesja jest wyjątkowa. Każdy poziom doświadczenia daje poczucie realnego postępu.",
            "Tryb wieloosobowy to coś, co wyróżnia tę grę. Grając z przyjaciółmi, zabawa wchodzi na zupełnie nowy poziom. Wspólne eksplorowanie świata gry czy rozwiązywanie zagadek to świetne doświadczenie. Możliwość rywalizacji w trybie PvP również daje dużo emocji. Serwery działają stabilnie, co zapewnia płynną rozgrywkę.",
            "Pogoda i cykl dnia oraz nocy w tej grze są imponujące. Każda zmiana warunków atmosferycznych wpływa na gameplay, co dodaje realizmu. W nocy przeciwnicy są trudniejsi, co zachęca do bardziej ostrożnej gry. Dodatkowo oprawa wizualna podczas burzy czy zachodu słońca zapiera dech w piersiach.",
            "Zadania w grze są naprawdę różnorodne i interesujące. Oprócz głównych misji, mamy mnóstwo pobocznych aktywności. Każde zadanie wprowadza coś nowego, co utrzymuje gracza w ciągłym zainteresowaniu. Warto poświęcić czas na eksplorację i wykonywanie dodatkowych misji.",
            "Możliwość odblokowania wielu zakończeń jest jednym z największych atutów tej gry. Każda decyzja, jaką podejmuję, ma realne konsekwencje. Dzięki temu gra zachęca do powrotu i odkrycia wszystkich możliwych ścieżek fabularnych. Jest to idealne dla graczy, którzy lubią eksplorować każdą opcję.",
            "Lokacje w tej grze to prawdziwe dzieła sztuki. Każde miejsce opowiada swoją historię i kryje sekrety. Świat gry jest pełen różnorodnych terenów, od gęstych lasów po zatopione miasta. Eksploracja daje niesamowitą satysfakcję i sprawia, że gra jest jeszcze bardziej wciągająca.",
            "Interfejs użytkownika jest intuicyjny i bardzo dobrze zaprojektowany. Nawigacja po menu jest prosta i szybka, co pozwala skupić się na rozgrywce. Wszystkie niezbędne informacje są łatwo dostępne, a dodatkowe opcje personalizacji to duży plus. Gra jest przyjazna zarówno dla nowych, jak i doświadczonych graczy.",
            "Ostatnia aktualizacja wprowadziła wiele nowych funkcji, które znacznie poprawiły grę. Dodano nowe lokacje, bronie i misje, co daje więcej możliwości rozgrywki. Optymalizacja została zauważalnie ulepszona, co pozytywnie wpływa na wydajność. Twórcy naprawdę słuchają społeczności graczy i dostarczają to, czego oczekują.",
            "Ukryte przedmioty i znajdźki w tej grze to coś, co bardzo cenię. Poszukiwanie sekretów to świetna zabawa, a nagrody są zawsze warte wysiłku. Gra zachęca do eksploracji i dokładnego przeszukiwania każdego zakątka. Dzięki temu świat gry wydaje się pełen życia i niespodzianek.",
            "System craftingu w tej grze to prawdziwa perełka. Możliwość tworzenia unikalnych przedmiotów i ulepszania ekwipunku dodaje głębi rozgrywce. Proces tworzenia jest intuicyjny, ale wymaga zdobywania odpowiednich surowców. Dzięki temu crafting nie tylko bawi, ale i nagradza graczy za ich wysiłek."
        ];


        public static readonly string[] SpamSuspicionContent = [
            "Ten post wygląda na spam – brak konkretnej treści.",
            "To konto publikowało podobne wpisy, może to być spam.",
            "Ciągle te same linki, wygląda to podejrzanie.",
            "Znów widzę te same wiadomości od tego użytkownika – możliwy spam.",
            "Treść posta nie ma związku z tematem, wygląda to na spam.",
            "Niepokojące, jak często ten użytkownik promuje tę samą stronę.",
            "Brak sensu w wypowiedzi – może to być automatyczny spam.",
            "Post składa się głównie z linków, raczej to nie jest przypadkowe.",
            "Podejrzanie podobne posty widziałem już wcześniej.",
            "Znów to samo kopiowane w różnych wątkach – możliwe, że to bot.",
            "Zawartość posta jest ogólna i nie wnosi nic do dyskusji, wygląda na spam.",
            "Linki w tej wiadomości prowadzą do podejrzanych stron.",
            "To konto tylko reklamuje, nic wartościowego nie wnosi do forum.",
            "Wydaje się, że to konto istnieje tylko po to, by spamować.",
            "Ten wpis powtarza się w wielu wątkach – wygląda na spam.",
            "Treść posta wygląda na wygenerowaną automatycznie.",
            "Wpis jest całkowicie nie na temat – może to być spam.",
            "To kolejna reklama tego samego produktu, możliwe, że to spam.",
            "Ciężko uwierzyć, że to prawdziwy użytkownik – wygląda jak bot.",
            "Brak jakiejkolwiek interakcji z innymi – wygląda na spamowe konto.",
            "Konto zostało stworzone niedawno i od razu reklamuje produkty.",
            "Powtarzające się wzorce wypowiedzi, bardzo przypomina spam.",
            "Jeden post na temat, a reszta to reklamy – raczej to nie przypadek.",
            "Kolejny raz widzę podobne linki, ewidentnie to spam.",
            "Wpisy użytkownika są bardzo schematyczne i bez wartości merytorycznej.",
            "Znów to samo konto promuje te same strony w różnych wątkach.",
            "Treść posta jest chaotyczna i nie wnosi nic wartościowego.",
            "Wszystkie posty tego użytkownika to praktycznie reklamy.",
            "Wygląda na to, że ten użytkownik spamuje różnymi linkami.",
            "Kolejny raz promowanie tej samej strony, wygląda to na spam."
        ];
    }
}
